# 24-bit colors
set-option -g default-terminal "$TERM"
set-option -sg terminal-overrides ",*:RGB"

# mouse support
set-option -g mouse on

# fix Home and End
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

# set <Prefix>
unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# source configuration with <Prefix>r
unbind-key r
bind-key r source-file ~/.config/tmux/tmux.conf \; display "re-sourced ~/.config/tmux/tmux.conf"

# indexing from 1, not 0
set-option -g base-index 1
set-option -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# <Prefix>X to close a window (like <Prefix>x to close a pane)
bind-key X confirm-before -p "kill-window #W? (y/n)" kill-window

# don't rename windows automatically
set-option -g allow-rename off

# vim keybindings for COPY mode (<Prefix>[)
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# launch panes/windows in current directory
unbind-key '"'
unbind-key %
bind-key - split-window -v -c "#{pane_current_path}"
bind-key | split-window -h -c "#{pane_current_path}"
bind-key c command-prompt -p "(new-window)" "new-window -c '#{pane_current_path}' \; rename-window '%%'"

# special way to launch MSYS2 UCRT64
bind-key u command-prompt -p "(new-window)" "new-window -c '#{pane_current_path}' 'cmd.exe /K C:/msys64/msys2_shell.cmd -defterm -here -no-start -ucrt64 -shell bash' \; rename-window '%%'"

# List of plugins:
set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-sensible'
set-option -g @plugin 'tmux-plugins/tmux-yank'
set-option -g @plugin 'christoomey/vim-tmux-navigator'

# <<----------------------------- EVERFOREST DARK SOFT ----------------------------->>
everforest_fg='#d3c6aa'
everforest_bg_dim='#293136'
everforest_bg0='#333c43'
everforest_bg1='#3a464c'
everforest_bg2='#434f55'
everforest_bg3='#4d5960'
everforest_bg4='#555f66'
everforest_bg5='#5d6b66'
everforest_bg_visual='#5c3f4f'
everforest_bg_red='#59464c'
everforest_bg_yellow='#55544a'
everforest_bg_green='#48584e'
everforest_bg_blue='#3f5865'
everforest_red='#e67e80'
everforest_orange='#e69875'
everforest_yellow='#dbbc7f'
everforest_green='#a7c080'
everforest_aqua='#83c092'
everforest_blue='#7fbbb3'
everforest_purple='#d699b6'
everforest_gray0='#7a8474'
everforest_gray1='#859289'
everforest_gray2='#9da9a0'

set-option -g status-position bottom
set-option -g status-justify absolute-centre

set-option -g status-style bg="${everforest_bg0}",fg="${everforest_fg}"

set-option -g message-style bg="${everforest_yellow}",fg="${everforest_bg_dim}"
set-option -g message-command-style bg="${everforest_yellow}",fg="${everforest_bg_dim}"

set-option -g pane-border-style fg="${everforest_bg1}"
set-option -g pane-active-border-style fg="${everforest_blue}"

set-option -g window-status-separator " "
set-option -g window-status-format " #I:#W "
set-option -g window-status-current-format " #[fg=${everforest_green},bold]#I:#W#[nobold] "
set-option -g status-left ""
set-option -g status-right ""
# <<----------------------------- EVERFOREST DARK SOFT ----------------------------->>


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
