# 24-bit colors
set-option -g default-terminal "$TERM"
set-option -sa terminal-overrides ",$TERM:Tc"

# mouse support
set-option -g mouse on

# fix Home and End
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

# set <Prefix>
unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# source configuration with <Prefix>r
unbind-key r
bind-key r source-file ~/.config/tmux/tmux.conf \; display "re-sourced ~/.config/tmux/tmux.conf"

# indexing from 1, not 0
set-option -g base-index 1
set-option -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# <Prefix>X to close a window (like <Prefix>x to close a pane)
bind-key X confirm-before -p "kill-window #W? (y/n)" kill-window

# don't rename windows automatically
set-option -g allow-rename off

# vim keybindings for COPY mode (<Prefix>[)
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# launch panes/windows in current directory
unbind-key '"'
unbind-key %
bind-key h split-window -v -c "#{pane_current_path}"
bind-key v split-window -h -c "#{pane_current_path}"
bind-key c command-prompt -p "(new-window)" "new-window -c '#{pane_current_path}' \; rename-window '%%'"

# List of plugins:
set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-sensible'
set-option -g @plugin 'tmux-plugins/tmux-yank'
set-option -g @plugin 'christoomey/vim-tmux-navigator'

# <<----------------------------- EVERFOREST DARK SOFT ----------------------------->>
EVERFOREST_FG='#D3C6AA'
EVERFOREST_BG_DIM='#293136'
EVERFOREST_BG0='#333C43'
EVERFOREST_BG1='#3A464C'
EVERFOREST_BG2='#434F55'
EVERFOREST_BG3='#4D5960'
EVERFOREST_BG4='#555F66'
EVERFOREST_BG5='#5D6B66'
EVERFOREST_BG_VISUAL='#5C3F4F'
EVERFOREST_BG_RED='#59464C'
EVERFOREST_BG_YELLOW='#55544A'
EVERFOREST_BG_GREEN='#48584E'
EVERFOREST_BG_BLUE='#3F5865'
EVERFOREST_RED='#E67E80'
EVERFOREST_ORANGE='#E69875'
EVERFOREST_YELLOW='#DBBC7F'
EVERFOREST_GREEN='#A7C080'
EVERFOREST_AQUA='#83C092'
EVERFOREST_BLUE='#7FBBB3'
EVERFOREST_PURPLE='#D699B6'
EVERFOREST_GRAY0='#7A8474'
EVERFOREST_GRAY1='#859289'
EVERFOREST_GRAY2='#9DA9A0'

set-option -g status-position bottom
set-option -g status-justify absolute-centre

set-option -g status-style bg="${EVERFOREST_GREEN}",fg="${EVERFOREST_BG_DIM}"

set-option -g message-style bg="${EVERFOREST_YELLOW}",fg="${EVERFOREST_BG_DIM}"
set-option -g message-command-style bg="${EVERFOREST_YELLOW}",fg="${EVERFOREST_BG_DIM}"

set-option -g pane-border-style fg="${EVERFOREST_BG1}"
set-option -g pane-active-border-style fg="${EVERFOREST_BLUE}"

set-option -g window-status-separator " "
set-option -g window-status-format " #I:#W "
set-option -g window-status-current-format "*#I:#[bold]#W#[nobold]*"
set-option -g status-left ""
set-option -g status-right ""
# <<----------------------------- EVERFOREST DARK SOFT ----------------------------->>


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
