# 24-bit colors
set-option -g default-terminal "$TERM"
set-option -sa terminal-overrides ",$TERM:Tc"

# mouse support
set-option -g mouse on

# position tmux statusline on top
set-option -g status-position top

# set <Prefix>
unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# source configuration with <Prefix>r
unbind-key r
bind-key r source-file ~/.config/tmux/tmux.conf \; display "re-sourced ~/.config/tmux/tmux.conf"

# indexing from 1, not 0
set-option -g base-index 1
set-option -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# <Prefix>X to close a window (like <Prefix>x to close a pane)
bind-key X confirm-before -p "kill-window #W? (y/n)" kill-window

# don't rename windows automatically
set-option -g allow-rename off

# vim keybindings for COPY mode (<Prefix>[)
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# launch panes/windows in current directory
unbind-key '"'
unbind-key %
bind-key h split-window -v -c "#{pane_current_path}"
bind-key v split-window -h -c "#{pane_current_path}"
bind-key c command-prompt -p "(new-window)" "new-window -c '#{pane_current_path}' \; rename-window '%%'"

# List of plugins:
set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-sensible'
set-option -g @plugin 'tmux-plugins/tmux-yank'
set-option -g @plugin 'christoomey/vim-tmux-navigator'

# <<----------------------------- EVERFOREST DARK SOFT ----------------------------->>
# TODO
# <<----------------------------- EVERFOREST DARK SOFT ----------------------------->>


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
